spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: My_Sql_D4t4b4s3 
    username: root
    url: 'jdbc:mysql://localhost:3306/fornecedor-paper'
  jpa:
    hibernate:
      ddl-auto: update
